sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: OoZ9sNNxpb6nFxsz4WS/GiNSlC5Ytl5gofuMAzbeCvNCncoj5pQDDa7ug9LGAU815AieXC+Y23Fl8QYTV3berPNQZAWyo0vmmN9T5Zz42ClY5zd7xGPqcGljLVA7xko9Aq8gCtKFLtjoLD+bvbuyqMFGDPwlOnM2byc1fNf9s/eOx3Onoh9yHwso4U6fyJiizzmYRtxIYwSYtF5MG6imby5Bc3jCpf0t/Pmm7ikkT/4ypttnkve4NHZc9fhRZK5jn7ZxwG9v9z5EV8mxzZNcRE8yUsDD8QVoH7bm+od12a3FOemz8hQEeEtHYd3QGSBu2i2d7ON+VNo1DmZ3eqNRs6R68OAQJJSGWifSBrs20aW/GE7hJZS7cnqwEHX1F+tXdbQOf6sNPKGcO8XsG/oFSZ50jw44Y/T0ag1qGchrs4t/0I8yQKjX5aBtCneCFrD2yqV6rDENaT+UZ1jmkB+35He8o/4Oh+u1YLLjzUa0dPd53oPE7aWjT4Zy7vambyVygJBs4Ri3iqrSG0iirOADkMtO5ZAiX3NX53PKYthiEvEX4LzE7Z7yXhYaiyrshAWNhHTq/RiI4j8BiYngHXwj16FATAu7B9fnep/Rlm7ssTHULsNG9uuVF19Lmlr33pPez//JJ1+VkQFqk8jgK8o/aD3auDlXBA69eDYQv+F7olI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/King-Edward-III_1770
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy